import{a as $,S as x,i}from"./assets/vendor-5401a4b0.js";(function(){const s=document.createElement("link").relList;if(s&&s.supports&&s.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))t(e);new MutationObserver(e=>{for(const r of e)if(r.type==="childList")for(const o of r.addedNodes)o.tagName==="LINK"&&o.rel==="modulepreload"&&t(o)}).observe(document,{childList:!0,subtree:!0});function a(e){const r={};return e.integrity&&(r.integrity=e.integrity),e.referrerPolicy&&(r.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?r.credentials="include":e.crossOrigin==="anonymous"?r.credentials="omit":r.credentials="same-origin",r}function t(e){if(e.ep)return;e.ep=!0;const r=a(e);fetch(e.href,r)}})();async function m(n,s,a){try{const t=`https://pixabay.com/api/?key=42459429-d6d7a0fe637ea3675bc35ddeb&q=${n}&page=${a}&per_page=${s}`;return(await $.get(t)).data}catch(t){console.log(t)}}function f({webformatURL:n,largeImageURL:s,likes:a,views:t,comments:e,downloads:r,tags:o}){return`<li>
        <div>
        <a href="${s}">
        <img src="${n}" alt="${o}">
        </a>
        </div>
        <div class="text-content">
        <p><span class="text-span">Likes</span><br>${a}</p>
        <p><span class="text-span">Views</span><br>${t}</p>
        <p><span class="text-span">Comments</span><br>${e}</p>
        <p><span class="text-span">Downloads</span><br>${r}</p>
        </div>
        </li>`}const v=document.querySelector(".searchForm"),c=document.querySelector(".css-loader"),p=document.querySelector(".galleryDetails"),l=document.querySelector(".load-more-btn"),g=new x("div a",{captionsData:"alt",captionDelay:250,preloading:!0});let h=1;const u=15;let y,d;v.addEventListener("submit",H);function H(n){n.preventDefault(),c.classList.add("loader"),p.innerHTML=null;const s=n.target.elements.name.value.trim();if(!s)return c.classList.remove("loader"),i.warning({message:"Must be filled"});m(s,u,h).then(t=>{if(!t.hits||t.hits.length===0)return i.error({message:"Sorry, there are no images matching your search query. Please try again!"});const r=t.hits.map(o=>f(o)).join("");p.innerHTML=r,y=s,d=h,l.classList.remove("visually-hidden"),t.totalHits<u&&(i.warning({message:`Only ${t.totalHits} pictures with your request were found`}),l.classList.add("visually-hidden")),g.refresh(),c.classList.remove("loader")}).catch(()=>{i.error({message:"Error occurred while fetching images. Please try again later!"})}).finally(()=>{c.classList.remove("loader")}),l.addEventListener("click",a);function a(){d++,m(y,u,d).then(t=>{const e=document.querySelector("li"),{height:r}=e.getBoundingClientRect(),L=t.hits.map(q=>f(q)).join("");p.insertAdjacentHTML("beforeend",L),window.scrollBy({top:r*2,behavior:"smooth"});const b=t.totalHits,w=Math.floor(b/u);d>w&&(i.error({message:"We're sorry, but you've reached the end of search results."}),l.classList.add("visually-hidden")),g.refresh()}).catch(()=>{i.error({message:"Error occurred while fetching images. Please try again later!"})})}v.reset()}
//# sourceMappingURL=commonHelpers.js.map
