import{a as L,S as b,i}from"./assets/vendor-5401a4b0.js";(function(){const r=document.createElement("link").relList;if(r&&r.supports&&r.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))a(e);new MutationObserver(e=>{for(const t of e)if(t.type==="childList")for(const n of t.addedNodes)n.tagName==="LINK"&&n.rel==="modulepreload"&&a(n)}).observe(document,{childList:!0,subtree:!0});function s(e){const t={};return e.integrity&&(t.integrity=e.integrity),e.referrerPolicy&&(t.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?t.credentials="include":e.crossOrigin==="anonymous"?t.credentials="omit":t.credentials="same-origin",t}function a(e){if(e.ep)return;e.ep=!0;const t=s(e);fetch(e.href,t)}})();async function f(o,r,s){try{const a=`https://pixabay.com/api/?key=42459429-d6d7a0fe637ea3675bc35ddeb&q=${o}&page=${s}&per_page=${r}`;return(await L.get(a)).data}catch(a){console.log(a)}}function g({webformatURL:o,largeImageURL:r,likes:s,views:a,comments:e,downloads:t,tags:n}){return`<li>
        <div>
        <a href="${r}">
        <img src="${o}" alt="${n}">
        </a>
        </div>
        <div class="text-content">
        <p><span class="text-span">Likes</span><br>${s}</p>
        <p><span class="text-span">Views</span><br>${a}</p>
        <p><span class="text-span">Comments</span><br>${e}</p>
        <p><span class="text-span">Downloads</span><br>${t}</p>
        </div>
        </li>`}const q=document.querySelector(".searchForm"),l=document.querySelector(".css-loader"),m=document.querySelector(".galleryDetails"),u=document.querySelector(".load-more-btn"),h=new b("div a",{captionsData:"alt",captionDelay:250,preloading:!0});let p=1;const d=15;let y,c;q.addEventListener("submit",w);function w(o){o.preventDefault(),l.classList.add("loader"),m.innerHTML=null;const r=o.target.elements.name.value.trim();if(!r)return l.classList.remove("loader"),i.warning({message:"Must be filled"});f(r,d,p).then(s=>{if(!s.hits||s.hits.length===0)return i.error({message:"Sorry, there are no images matching your search query. Please try again!"});const e=s.hits.map(t=>g(t)).join("");m.innerHTML=e,y=r,c=p,u.classList.remove("visually-hidden"),s.totalHits<d&&u.classList.add("visually-hidden"),h.refresh(),l.classList.remove("loader")}).catch(()=>{i.error({message:"Error occurred while fetching images. Please try again later!"})}).finally(()=>{l.classList.remove("loader"),o.target.elements.name.value=null})}u.addEventListener("click",$);function $(){c++,f(y,d,c).then(o=>{const r=document.querySelector("li"),{height:s}=r.getBoundingClientRect(),a=o.totalHits,e=Math.floor(a/d);c>e&&(i.error({message:"We're sorry, but you've reached the end of search results."}),u.classList.add("visually-hidden"));const n=o.hits.map(v=>g(v)).join("");m.insertAdjacentHTML("beforeend",n),window.scrollBy({top:s*2,behavior:"smooth"}),h.refresh()}).catch(()=>{i.error({message:"Error occurred while fetching images. Please try again later!"})})}
//# sourceMappingURL=commonHelpers.js.map
